pub type Span = std::ops::Range<usize>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Token<'a> {
    // Keywords
    OpenQasm,
    Include,
    DefCalGrammar,
    Def,
    Cal,
    DefCal,
    Gate,
    Extern,
    Box,
    Let,
    Break,
    Continue,
    If,
    Else,
    End,
    Return,
    For,
    While,
    In,
    Switch,
    Case,
    Default,
    Nop,
    Pragma,
    AnnotationKeyword(&'a str),

    // Type keywords
    Input,
    Output,
    Const,
    Readonly,
    Mutable,
    Qreg,
    Qubit,
    Creg,
    Bool,
    Bit,
    Int,
    Uint,
    Float,
    Angle,
    Complex,
    Array,
    Void,
    Duration,
    Stretch,

    // Builtin identifiers and operations
    Gphase,
    Inv,
    Pow,
    Ctrl,
    Negctrl,
    Dim,
    Durationof,
    Delay,
    Reset,
    Measure,
    Barrier,
    Imag,

    // Literals
    True,
    False,
    BinaryIntegerLiteral(&'a str),
    OctalIntegerLiteral(&'a str),
    DecimalIntegerLiteral(&'a str),
    HexIntegerLiteral(&'a str),
    FloatLiteral(&'a str),
    ImaginaryLiteral(&'a str),
    TimingLiteral(&'a str),
    BitstringLiteral(&'a str),
    Identifier(&'a str),
    HardwareQubit(&'a str),

    // Symbols
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    LParen,
    RParen,
    Colon,
    Semicolon,
    Dot,
    Comma,
    Equals,
    Arrow,
    Plus,
    DoublePlus,
    Minus,
    Asterisk,
    DoubleAsterisk,
    Slash,
    Percent,
    Pipe,
    DoublePipe,
    Ampersand,
    DoubleAmpersand,
    Caret,
    At,
    Tilde,
    ExclamationPoint,

    // Multi-value operators
    DoubleEquals,
    ExclamationEquals,
    PlusEquals,
    MinusEquals,
    AsteriskEquals,
    SlashEquals,
    AmpersandEquals,
    PipeEquals,
    CaretEquals,
    LeftShiftEquals,
    RightShiftEquals,
    PercentEquals,
    DoubleAsteriskEquals,
    GreaterThan,
    LessThan,
    GreaterThanEquals,
    LessThanEquals,
    DoubleGreater,
    DoubleLess,

    // Mode-specific tokens
    VersionSpecifier(&'a str),
    StringLiteral(&'a str),
    RemainingLineContent(&'a str),
    CalibrationBlock(&'a str),

    // Comments
    LineComment(&'a str),
    BlockComment(&'a str),
}
